### ISSUE TITLE
Add a 404 page 

### ISSUE THREAD

**Issue by bonface221** [bonface221/harryporter#25]
Match all routes that are not in the defined routes and add a 404 page 

![image](https://github.com/bonface221/harryporter/assets/98006412/14fa7804-c53b-4eeb-a4e5-d486da3e426f)

**Comment by devAbdulsalam** [comment]
Fixed
![Screenshot (9)](https://github.com/bonface221/harryporter/assets/70317190/e4ab9fa5-a3c4-46d6-b747-5a8079e8f708)

**Comment by bonface221** [comment]
Nice work
