### ISSUE TITLE
Add no houses available to the characters with no houses 🥳😊

### ISSUE THREAD

**Issue by bonface221** [bonface221/harryporter#5]
Some characters don't have houses add a no house available to it 🥳

![image](https://github.com/bonface221/harryporter/assets/98006412/440287b2-89a8-4a5e-bb2c-890e3f67a0e8)

**Comment by nirav-v** [comment]
Submitted a PR for this

**Comment by bonface221** [comment]
Done it's merged check the changes on the live url
